window.BP_DATA = [
  {
    "ReadingID": 118,
    "Date": "2025-07-23 05:00:01 pm",
    "Sys": 181,
    "Dia": 120,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Hypertensive Crisis",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 61,
    "FormComments": "This is test data to test for a Hypertensive Crisis reading and a 'widened' pulse pressure reading.  Ignore if you see this reading.",
    "PulsePressureCategory": "Widened"
  },
  {
    "ReadingID": 119,
    "Date": "2025-07-24 05:00:01 pm",
    "Sys": 111,
    "Dia": 89,
    "BPM": 57,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Bradycardia",
    "gPulsePressure": 102,
    "FormComments": "This is test data to simulate a Brachadya reading, and a 'very widened' pulse pressure reading.  Ignore if you see this reading.",
    "PulsePressureCategory": "Very Widened"
  },
  {
    "ReadingID": 120,
    "Date": "2025-07-25 05:00:01 pm",
    "Sys": 111,
    "Dia": 89,
    "BPM": 105,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Tachycardia",
    "gPulsePressure": 22,
    "FormComments": "This is test data to simulate a Tachycardia reading.  Ignore if you see this reading.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 121,
    "Date": "2025-07-08 05:00:01 pm",
    "Sys": 114,
    "Dia": 87,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "This is test data so the calendar viz MONTH() doesn't collapse in july 2025 (stupid tableau needs 1 day per month with 2 readings)",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 1,
    "Date": "2025-07-08 05:00:00 pm",
    "Sys": 114,
    "Dia": 87,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 2,
    "Date": "2025-07-09 05:00:00 pm",
    "Sys": 101,
    "Dia": 72,
    "BPM": 76,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 3,
    "Date": "2025-07-10 05:00:00 pm",
    "Sys": 111,
    "Dia": 80,
    "BPM": 80,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 4,
    "Date": "2025-07-11 05:00:00 pm",
    "Sys": 101,
    "Dia": 74,
    "BPM": 68,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 5,
    "Date": "2025-07-12 05:00:00 pm",
    "Sys": 107,
    "Dia": 73,
    "BPM": 83,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 6,
    "Date": "2025-07-13 05:00:00 pm",
    "Sys": 103,
    "Dia": 82,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 21,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 7,
    "Date": "2025-07-14 05:00:00 pm",
    "Sys": 117,
    "Dia": 85,
    "BPM": 77,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 8,
    "Date": "2025-07-15 05:00:00 pm",
    "Sys": 99,
    "Dia": 71,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 28,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 9,
    "Date": "2025-07-16 05:00:00 pm",
    "Sys": 112,
    "Dia": 76,
    "BPM": 85,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 10,
    "Date": "2025-07-18 05:00:00 pm",
    "Sys": 101,
    "Dia": 74,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 11,
    "Date": "2025-07-19 05:00:00 pm",
    "Sys": 96,
    "Dia": 74,
    "BPM": 81,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 22,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 12,
    "Date": "2025-07-22 05:00:00 pm",
    "Sys": 115,
    "Dia": 86,
    "BPM": 67,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 13,
    "Date": "2025-07-27 05:00:00 pm",
    "Sys": 102,
    "Dia": 76,
    "BPM": 66,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 14,
    "Date": "2025-07-28 05:00:00 pm",
    "Sys": 116,
    "Dia": 82,
    "BPM": 72,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 15,
    "Date": "2025-07-29 05:00:00 pm",
    "Sys": 103,
    "Dia": 67,
    "BPM": 82,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 16,
    "Date": "2025-07-30 05:00:00 pm",
    "Sys": 96,
    "Dia": 64,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 17,
    "Date": "2025-07-31 05:00:00 pm",
    "Sys": 119,
    "Dia": 93,
    "BPM": 65,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 18,
    "Date": "2025-08-01 05:00:00 pm",
    "Sys": 127,
    "Dia": 86,
    "BPM": 63,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 41,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 19,
    "Date": "2025-08-01 10:00:00 pm",
    "Sys": 113,
    "Dia": 78,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 35,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 20,
    "Date": "2025-08-02 07:00:00 pm",
    "Sys": 122,
    "Dia": 89,
    "BPM": 68,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 21,
    "Date": "2025-08-02 11:00:00 pm",
    "Sys": 122,
    "Dia": 88,
    "BPM": 66,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 22,
    "Date": "2025-08-03 05:00:00 pm",
    "Sys": 99,
    "Dia": 71,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 28,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 23,
    "Date": "2025-08-04 05:00:00 pm",
    "Sys": 107,
    "Dia": 75,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 24,
    "Date": "2025-08-05 05:00:00 pm",
    "Sys": 121,
    "Dia": 95,
    "BPM": 81,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 25,
    "Date": "2025-08-05 10:00:00 pm",
    "Sys": 112,
    "Dia": 80,
    "BPM": 73,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 26,
    "Date": "2025-08-06 08:00:00 pm",
    "Sys": 105,
    "Dia": 75,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 27,
    "Date": "2025-08-07 05:00:00 pm",
    "Sys": 109,
    "Dia": 86,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 23,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 28,
    "Date": "2025-08-07 10:00:00 pm",
    "Sys": 100,
    "Dia": 76,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 24,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 29,
    "Date": "2025-08-08 05:00:00 pm",
    "Sys": 105,
    "Dia": 80,
    "BPM": 63,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 25,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 30,
    "Date": "2025-08-09 05:00:00 pm",
    "Sys": 113,
    "Dia": 83,
    "BPM": 69,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 31,
    "Date": "2025-08-09 10:00:00 pm",
    "Sys": 105,
    "Dia": 84,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 21,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 32,
    "Date": "2025-08-10 05:00:00 pm",
    "Sys": 127,
    "Dia": 96,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 33,
    "Date": "2025-08-10 10:00:00 pm",
    "Sys": 101,
    "Dia": 75,
    "BPM": 81,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 34,
    "Date": "2025-08-11 07:00:00 pm",
    "Sys": 117,
    "Dia": 81,
    "BPM": 78,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 35,
    "Date": "2025-08-11 10:00:00 pm",
    "Sys": 113,
    "Dia": 80,
    "BPM": 73,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 36,
    "Date": "2025-08-12 05:00:00 pm",
    "Sys": 106,
    "Dia": 76,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 37,
    "Date": "2025-08-13 08:00:00 pm",
    "Sys": 109,
    "Dia": 81,
    "BPM": 74,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 28,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 38,
    "Date": "2025-08-13 11:00:00 pm",
    "Sys": 110,
    "Dia": 78,
    "BPM": 72,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 39,
    "Date": "2025-08-14 11:00:00 pm",
    "Sys": 116,
    "Dia": 84,
    "BPM": 70,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 40,
    "Date": "2025-08-15 07:00:00 pm",
    "Sys": 109,
    "Dia": 81,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 28,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 41,
    "Date": "2025-08-15 11:00:00 pm",
    "Sys": 108,
    "Dia": 77,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 42,
    "Date": "2025-08-16 05:00:00 pm",
    "Sys": 117,
    "Dia": 85,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 43,
    "Date": "2025-08-16 11:00:00 pm",
    "Sys": 101,
    "Dia": 76,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 25,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 44,
    "Date": "2025-08-17 05:00:00 pm",
    "Sys": 122,
    "Dia": 87,
    "BPM": 67,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 35,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 45,
    "Date": "2025-08-17 10:00:00 pm",
    "Sys": 110,
    "Dia": 76,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 46,
    "Date": "2025-08-18 07:00:00 pm",
    "Sys": 108,
    "Dia": 77,
    "BPM": 70,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 47,
    "Date": "2025-08-19 05:00:00 pm",
    "Sys": 121,
    "Dia": 83,
    "BPM": 68,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 38,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 48,
    "Date": "2025-08-19 10:00:00 pm",
    "Sys": 110,
    "Dia": 87,
    "BPM": 63,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 23,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 49,
    "Date": "2025-08-20 06:00:00 pm",
    "Sys": 134,
    "Dia": 96,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 38,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 50,
    "Date": "2025-08-20 10:00:00 pm",
    "Sys": 112,
    "Dia": 76,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 51,
    "Date": "2025-08-21 05:00:00 pm",
    "Sys": 115,
    "Dia": 85,
    "BPM": 62,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 52,
    "Date": "2025-08-22 05:00:00 pm",
    "Sys": 122,
    "Dia": 87,
    "BPM": 69,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 35,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 53,
    "Date": "2025-08-22 10:00:00 pm",
    "Sys": 110,
    "Dia": 75,
    "BPM": 67,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 35,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 54,
    "Date": "2025-08-23 05:00:00 pm",
    "Sys": 119,
    "Dia": 93,
    "BPM": 66,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 55,
    "Date": "2025-08-23 10:00:00 pm",
    "Sys": 93,
    "Dia": 70,
    "BPM": 64,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 23,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 56,
    "Date": "2025-08-24 05:00:00 pm",
    "Sys": 107,
    "Dia": 76,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 57,
    "Date": "2025-08-24 10:00:00 pm",
    "Sys": 100,
    "Dia": 71,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 58,
    "Date": "2025-08-25 05:00:00 pm",
    "Sys": 100,
    "Dia": 75,
    "BPM": 69,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 25,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 59,
    "Date": "2025-08-25 10:00:00 pm",
    "Sys": 105,
    "Dia": 83,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 22,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 60,
    "Date": "2025-08-26 05:00:00 pm",
    "Sys": 104,
    "Dia": 76,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 28,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 61,
    "Date": "2025-08-27 11:00:00 pm",
    "Sys": 98,
    "Dia": 75,
    "BPM": 72,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 23,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 62,
    "Date": "2025-08-28 05:00:00 pm",
    "Sys": 107,
    "Dia": 80,
    "BPM": 69,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 63,
    "Date": "2025-08-28 11:00:00 pm",
    "Sys": 96,
    "Dia": 70,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 64,
    "Date": "2025-08-29 05:00:00 pm",
    "Sys": 111,
    "Dia": 82,
    "BPM": 63,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 65,
    "Date": "2025-08-30 10:00:00 pm",
    "Sys": 112,
    "Dia": 81,
    "BPM": 81,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 66,
    "Date": "2025-08-31 05:00:00 pm",
    "Sys": 114,
    "Dia": 84,
    "BPM": 69,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 67,
    "Date": "2025-09-01 06:00:00 pm",
    "Sys": 123,
    "Dia": 97,
    "BPM": 77,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 68,
    "Date": "2025-09-01 10:00:00 pm",
    "Sys": 116,
    "Dia": 83,
    "BPM": 71,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 69,
    "Date": "2025-09-02 05:00:00 pm",
    "Sys": 112,
    "Dia": 81,
    "BPM": 69,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 70,
    "Date": "2025-09-03 05:00:00 pm",
    "Sys": 135,
    "Dia": 89,
    "BPM": 75,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 46,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 71,
    "Date": "2025-09-03 10:00:00 pm",
    "Sys": 100,
    "Dia": 73,
    "BPM": 70,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 72,
    "Date": "2025-09-04 05:00:00 pm",
    "Sys": 119,
    "Dia": 84,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 35,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 73,
    "Date": "2025-09-04 10:00:00 pm",
    "Sys": 107,
    "Dia": 80,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 74,
    "Date": "2025-09-05 05:00:00 pm",
    "Sys": 113,
    "Dia": 88,
    "BPM": 73,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 25,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 75,
    "Date": "2025-09-05 10:00:00 pm",
    "Sys": 120,
    "Dia": 71,
    "BPM": 79,
    "Workday": "No",
    "ReadingCategory": "Elevated",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 49,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 76,
    "Date": "2025-09-06 10:00:00 pm",
    "Sys": 105,
    "Dia": 80,
    "BPM": 71,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 25,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 77,
    "Date": "2025-09-07 05:00:00 pm",
    "Sys": 108,
    "Dia": 74,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 78,
    "Date": "2025-09-07 10:00:00 pm",
    "Sys": 111,
    "Dia": 61,
    "BPM": 71,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 50,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 79,
    "Date": "2025-09-08 11:00:00 am",
    "Sys": 135,
    "Dia": 101,
    "BPM": 88,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 80,
    "Date": "2025-09-08 05:00:00 pm",
    "Sys": 113,
    "Dia": 83,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 81,
    "Date": "2025-09-09 05:00:00 pm",
    "Sys": 129,
    "Dia": 77,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Elevated",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 52,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 82,
    "Date": "2025-09-09 10:00:00 pm",
    "Sys": 107,
    "Dia": 80,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 83,
    "Date": "2025-09-10 11:00:00 am",
    "Sys": 152,
    "Dia": 109,
    "BPM": 89,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 43,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 84,
    "Date": "2025-09-10 02:00:00 pm",
    "Sys": 122,
    "Dia": 91,
    "BPM": 95,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 85,
    "Date": "2025-09-10 05:00:00 pm",
    "Sys": 104,
    "Dia": 76,
    "BPM": 80,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 28,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 86,
    "Date": "2025-09-10 10:00:00 pm",
    "Sys": 108,
    "Dia": 78,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 87,
    "Date": "2025-09-11 05:00:00 pm",
    "Sys": 120,
    "Dia": 83,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 88,
    "Date": "2025-09-12 05:00:00 pm",
    "Sys": 134,
    "Dia": 97,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 89,
    "Date": "2025-09-12 11:00:00 pm",
    "Sys": 134,
    "Dia": 90,
    "BPM": 78,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 44,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 90,
    "Date": "2025-09-13 05:00:00 pm",
    "Sys": 102,
    "Dia": 76,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 91,
    "Date": "2025-09-14 05:00:00 pm",
    "Sys": 117,
    "Dia": 85,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 92,
    "Date": "2025-09-15 05:00:00 pm",
    "Sys": 91,
    "Dia": 85,
    "BPM": 72,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 6,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 93,
    "Date": "2025-09-16 05:00:00 pm",
    "Sys": 103,
    "Dia": 76,
    "BPM": 77,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 94,
    "Date": "2025-09-17 05:00:00 pm",
    "Sys": 107,
    "Dia": 86,
    "BPM": 87,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 21,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 95,
    "Date": "2025-09-17 11:00:00 pm",
    "Sys": 121,
    "Dia": 84,
    "BPM": 85,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 96,
    "Date": "2025-09-18 03:00:00 pm",
    "Sys": 124,
    "Dia": 93,
    "BPM": 83,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 97,
    "Date": "2025-09-19 05:00:00 pm",
    "Sys": 110,
    "Dia": 85,
    "BPM": 80,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 25,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 98,
    "Date": "2025-09-19 11:00:00 pm",
    "Sys": 90,
    "Dia": 67,
    "BPM": 72,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 23,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 99,
    "Date": "2025-09-20 02:00:00 pm",
    "Sys": 156,
    "Dia": 102,
    "BPM": 67,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 54,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 100,
    "Date": "2025-09-20 05:00:00 pm",
    "Sys": 93,
    "Dia": 63,
    "BPM": 68,
    "Workday": "no",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 101,
    "Date": "2025-09-21 05:00:00 pm",
    "Sys": 108,
    "Dia": 73,
    "BPM": 85,
    "Workday": "no",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 35,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 102,
    "Date": "2025-09-22 05:00:00 pm",
    "Sys": 108,
    "Dia": 79,
    "BPM": 75,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 103,
    "Date": "2025-09-23 05:00:00 pm",
    "Sys": 101,
    "Dia": 79,
    "BPM": 73,
    "Workday": "no",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 22,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 104,
    "Date": "2025-09-23 09:00:00 pm",
    "Sys": 93,
    "Dia": 70,
    "BPM": 68,
    "Workday": "no",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 23,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 105,
    "Date": "2025-09-24 03:00:00 pm",
    "Sys": 108,
    "Dia": 79,
    "BPM": 87,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 106,
    "Date": "2025-09-25 11:00:00 pm",
    "Sys": 93,
    "Dia": 69,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 24,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 107,
    "Date": "2025-09-26 05:00:00 pm",
    "Sys": 118,
    "Dia": 87,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 108,
    "Date": "2025-09-27 05:00:00 pm",
    "Sys": 93,
    "Dia": 71,
    "BPM": 65,
    "Workday": "no",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 22,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 109,
    "Date": "2025-09-28 05:00:00 pm",
    "Sys": 111,
    "Dia": 85,
    "BPM": 81,
    "Workday": "no",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 110,
    "Date": "2025-09-29 05:00:00 pm",
    "Sys": 107,
    "Dia": 75,
    "BPM": 74,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 111,
    "Date": "2025-09-30 05:00:00 pm",
    "Sys": 109,
    "Dia": 78,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 112,
    "Date": "2025-10-01 05:00:00 pm",
    "Sys": 142,
    "Dia": 104,
    "BPM": 78,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 38,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 113,
    "Date": "2025-10-01 11:00:00 pm",
    "Sys": 98,
    "Dia": 77,
    "BPM": 76,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 21,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 114,
    "Date": "2025-10-02 05:00:00 pm",
    "Sys": 115,
    "Dia": 85,
    "BPM": 69,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 115,
    "Date": "2025-10-03 05:00:00 pm",
    "Sys": 103,
    "Dia": 71,
    "BPM": 77,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 116,
    "Date": "2025-10-04 05:00:00 pm",
    "Sys": 101,
    "Dia": 70,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 117,
    "Date": "2025-10-05 05:00:00 pm",
    "Sys": 111,
    "Dia": 89,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 22,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 122,
    "Date": "2025-10-05 11:00:00 pm",
    "Sys": 106,
    "Dia": 79,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 123,
    "Date": "2025-10-06 05:00:00 pm",
    "Sys": 115,
    "Dia": 76,
    "BPM": 70,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 124,
    "Date": "2025-10-07 05:00:00 pm",
    "Sys": 113,
    "Dia": 83,
    "BPM": 77,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 125,
    "Date": "2025-10-07 11:30:00 pm",
    "Sys": 101,
    "Dia": 71,
    "BPM": 66,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 126,
    "Date": "2025-10-08 05:00:00 pm",
    "Sys": 121,
    "Dia": 91,
    "BPM": 69,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 127,
    "Date": "2025-10-09 05:00:00 pm",
    "Sys": 105,
    "Dia": 74,
    "BPM": 65,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 128,
    "Date": "2025-10-10 06:12:20 pm",
    "Sys": 146,
    "Dia": 103,
    "BPM": 75,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 43,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 129,
    "Date": "2025-10-10 11:23:54 pm",
    "Sys": 101,
    "Dia": 77,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 24,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 130,
    "Date": "2025-10-11 05:15:27 pm",
    "Sys": 104,
    "Dia": 76,
    "BPM": 70,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 28,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 131,
    "Date": "2025-10-12 07:03:06 pm",
    "Sys": 107,
    "Dia": 85,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 22,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 132,
    "Date": "2025-10-13 05:01:37 pm",
    "Sys": 124,
    "Dia": 88,
    "BPM": 67,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 133,
    "Date": "2025-10-14 06:06:59 pm",
    "Sys": 108,
    "Dia": 71,
    "BPM": 74,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 134,
    "Date": "2025-10-15 01:43:09 pm",
    "Sys": 101,
    "Dia": 79,
    "BPM": 72,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 22,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 135,
    "Date": "2025-10-15 05:08:47 pm",
    "Sys": 114,
    "Dia": 83,
    "BPM": 73,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 136,
    "Date": "2025-10-16 05:28:00 pm",
    "Sys": 135,
    "Dia": 94,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 41,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 137,
    "Date": "2025-10-17 05:15:24 pm",
    "Sys": 121,
    "Dia": 89,
    "BPM": 64,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 138,
    "Date": "2025-10-18 05:15:41 pm",
    "Sys": 113,
    "Dia": 87,
    "BPM": 77,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 139,
    "Date": "2025-10-19 06:24:52 pm",
    "Sys": 109,
    "Dia": 83,
    "BPM": 71,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 140,
    "Date": "2025-10-19 09:42:07 pm",
    "Sys": 110,
    "Dia": 77,
    "BPM": 80,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 141,
    "Date": "2025-10-20 07:27:26 pm",
    "Sys": 129,
    "Dia": 91,
    "BPM": 70,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 38,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 142,
    "Date": "2025-10-21 05:42:50 pm",
    "Sys": 122,
    "Dia": 89,
    "BPM": 80,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 143,
    "Date": "2025-10-22 05:12:15 pm",
    "Sys": 120,
    "Dia": 86,
    "BPM": 75,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 144,
    "Date": "2025-10-23 05:01:41 pm",
    "Sys": 142,
    "Dia": 97,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 45,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 145,
    "Date": "2025-10-24 05:51:34 pm",
    "Sys": 104,
    "Dia": 72,
    "BPM": 69,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 146,
    "Date": "2025-10-25 05:01:50 pm",
    "Sys": 122,
    "Dia": 84,
    "BPM": 83,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 38,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 147,
    "Date": "2025-10-26 07:49:29 pm",
    "Sys": 114,
    "Dia": 84,
    "BPM": 84,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 148,
    "Date": "2025-10-27 06:14:08 pm",
    "Sys": 129,
    "Dia": 90,
    "BPM": 73,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 149,
    "Date": "2025-10-28 05:02:31 pm",
    "Sys": 127,
    "Dia": 89,
    "BPM": 66,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 38,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 150,
    "Date": "2025-10-29 05:31:21 pm",
    "Sys": 133,
    "Dia": 94,
    "BPM": 77,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 151,
    "Date": "2025-10-30 05:01:26 pm",
    "Sys": 130,
    "Dia": 92,
    "BPM": 76,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 38,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 152,
    "Date": "2025-10-31 05:46:32 pm",
    "Sys": 132,
    "Dia": 95,
    "BPM": 62,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 153,
    "Date": "2025-11-02 05:35:17 pm",
    "Sys": 127,
    "Dia": 96,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 154,
    "Date": "2025-11-03 05:11:49 pm",
    "Sys": 113,
    "Dia": 81,
    "BPM": 69,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 32,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 155,
    "Date": "2025-11-04 10:42:52 pm",
    "Sys": 104,
    "Dia": 76,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 28,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 156,
    "Date": "2025-11-05 05:28:01 pm",
    "Sys": 125,
    "Dia": 91,
    "BPM": 74,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 157,
    "Date": "2025-11-06 05:21:56 pm",
    "Sys": 137,
    "Dia": 101,
    "BPM": 82,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 158,
    "Date": "2025-11-07 05:11:36 pm",
    "Sys": 139,
    "Dia": 95,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 44,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 159,
    "Date": "2025-11-08 05:06:20 pm",
    "Sys": 121,
    "Dia": 85,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 160,
    "Date": "2025-11-09 06:01:49 pm",
    "Sys": 111,
    "Dia": 84,
    "BPM": 68,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 161,
    "Date": "2025-11-13 05:01:23 pm",
    "Sys": 131,
    "Dia": 92,
    "BPM": 77,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 162,
    "Date": "2025-11-13 09:01:29 pm",
    "Sys": 119,
    "Dia": 86,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 163,
    "Date": "2025-11-14 05:36:59 pm",
    "Sys": 137,
    "Dia": 98,
    "BPM": 68,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 164,
    "Date": "2025-11-15 05:25:30 pm",
    "Sys": 145,
    "Dia": 101,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 44,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 165,
    "Date": "2025-11-16 05:26:26 pm",
    "Sys": 131,
    "Dia": 94,
    "BPM": 77,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 166,
    "Date": "2025-11-17 06:14:46 pm",
    "Sys": 122,
    "Dia": 83,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 167,
    "Date": "2025-11-18 05:11:19 pm",
    "Sys": 128,
    "Dia": 87,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 41,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 168,
    "Date": "2025-11-19 05:09:42 pm",
    "Sys": 138,
    "Dia": 96,
    "BPM": 72,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 42,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 169,
    "Date": "2025-11-20 05:41:35 pm",
    "Sys": 118,
    "Dia": 82,
    "BPM": 73,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 170,
    "Date": "2025-11-20 07:56:16 pm",
    "Sys": 116,
    "Dia": 87,
    "BPM": 71,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 171,
    "Date": "2025-11-21 09:07:25 pm",
    "Sys": 100,
    "Dia": 69,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 172,
    "Date": "2025-11-22 05:33:36 pm",
    "Sys": 127,
    "Dia": 88,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "Spent all day in bed with AI trying to make tableau analysis charts.  Pressure may be so high because I'm both frustrated and impressed by AI.  Giving up on Claude and going with Gemini as google is better with medical data.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 173,
    "Date": "2025-11-23 05:01:14 pm",
    "Sys": 135,
    "Dia": 84,
    "BPM": 78,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 51,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 174,
    "Date": "2025-11-23 09:12:43 pm",
    "Sys": 121,
    "Dia": 81,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 40,
    "FormComments": "Not a strenuous day.  Did groceries, and spent the day in tableau trying to get the Standard Deviation features in my dashboard working.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 175,
    "Date": "2025-11-24 05:01:50 pm",
    "Sys": 142,
    "Dia": 88,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 54,
    "FormComments": "Why is it so high today?",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 176,
    "Date": "2025-11-24 10:07:20 pm",
    "Sys": 107,
    "Dia": 74,
    "BPM": 85,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "Light headed when I stood up.  I went from Hyper2 to Normal in just 5 hours.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 177,
    "Date": "2025-11-25 11:00:25 am",
    "Sys": 139,
    "Dia": 96,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 43,
    "FormComments": "I had a tooth extracted 30 mins prior to this reading.",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 178,
    "Date": "2025-11-25 05:11:04 pm",
    "Sys": 139,
    "Dia": 92,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 47,
    "FormComments": "woke up after a nap.",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 179,
    "Date": "2025-11-25 06:18:37 pm",
    "Sys": 127,
    "Dia": 94,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "1 hour after nap, stood up; light headed.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 180,
    "Date": "2025-11-26 05:29:13 pm",
    "Sys": 135,
    "Dia": 87,
    "BPM": 80,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 48,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 181,
    "Date": "2025-11-27 05:01:38 pm",
    "Sys": 127,
    "Dia": 96,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 182,
    "Date": "2025-11-28 06:08:42 pm",
    "Sys": 117,
    "Dia": 88,
    "BPM": 79,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "Sad day - I accidentally overwrote my tableau workbook and had to rebuild it.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 183,
    "Date": "2025-11-29 07:22:47 pm",
    "Sys": 125,
    "Dia": 85,
    "BPM": 79,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 40,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 184,
    "Date": "2025-11-30 05:12:31 pm",
    "Sys": 142,
    "Dia": 94,
    "BPM": 77,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 48,
    "FormComments": "Not a strenuous day.  Don't know why it's so high again!",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 185,
    "Date": "2025-11-30 08:59:57 pm",
    "Sys": 114,
    "Dia": 80,
    "BPM": 73,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 186,
    "Date": "2025-12-01 02:48:59 am",
    "Sys": 99,
    "Dia": 76,
    "BPM": 69,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 23,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 187,
    "Date": "2025-12-01 03:11:43 pm",
    "Sys": 130,
    "Dia": 96,
    "BPM": 82,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 188,
    "Date": "2025-12-02 05:41:51 pm",
    "Sys": 122,
    "Dia": 91,
    "BPM": 80,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 189,
    "Date": "2025-12-02 06:55:27 pm",
    "Sys": 106,
    "Dia": 79,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "How did I drop from Hyper2 to Normal in 1 hour?",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 190,
    "Date": "2025-12-03 06:42:14 pm",
    "Sys": 112,
    "Dia": 87,
    "BPM": 92,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 25,
    "FormComments": "Whoa.  Why is my bpm so high?  It wasn't strenuous today, but I was out for 11 hours.  I feel fine.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 191,
    "Date": "2025-12-04 12:55:45 am",
    "Sys": 96,
    "Dia": 72,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 24,
    "FormComments": "Light headed.  Seems to happen at night only lately.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 192,
    "Date": "2025-12-04 05:21:36 pm",
    "Sys": 115,
    "Dia": 84,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 193,
    "Date": "2025-12-06 12:22:21 am",
    "Sys": 131,
    "Dia": 88,
    "BPM": 83,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 43,
    "FormComments": "Feeling very shaky.  worked hard today; long day, poor high-sodium diet.",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 194,
    "Date": "2025-12-06 05:09:02 pm",
    "Sys": 135,
    "Dia": 88,
    "BPM": 68,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 47,
    "FormComments": "BPM is down over similar reading last night - feel fine; minimal activity today.",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 195,
    "Date": "2025-12-07 05:33:04 pm",
    "Sys": 124,
    "Dia": 91,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "Just finished baking so not a strenuous day.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 196,
    "Date": "2025-12-08 07:51:56 am",
    "Sys": 103,
    "Dia": 72,
    "BPM": 81,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 31,
    "FormComments": "just woke up.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 197,
    "Date": "2025-12-08 08:21:54 pm",
    "Sys": 121,
    "Dia": 88,
    "BPM": 70,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 198,
    "Date": "2025-12-09 09:39:16 pm",
    "Sys": 138,
    "Dia": 96,
    "BPM": 76,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 42,
    "FormComments": "Just got home from working late - probably why so high.",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 199,
    "Date": "2025-12-10 06:34:30 pm",
    "Sys": 143,
    "Dia": 96,
    "BPM": 83,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 47,
    "FormComments": "Worked today, but it shouldn't be this high!",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 200,
    "Date": "2025-12-10 11:18:07 pm",
    "Sys": 134,
    "Dia": 94,
    "BPM": 71,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 40,
    "FormComments": "I took this reading a few hours after the last.  It is still unusually high after a stress-free evening.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 201,
    "Date": "2025-12-11 06:44:50 pm",
    "Sys": 107,
    "Dia": 86,
    "BPM": 78,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 21,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 202,
    "Date": "2025-12-12 05:22:37 pm",
    "Sys": 137,
    "Dia": 103,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 203,
    "Date": "2025-12-12 09:25:30 pm",
    "Sys": 108,
    "Dia": 92,
    "BPM": 78,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 16,
    "FormComments": "Felt light headed when I stood up.  Compare to the reading before, and note the pulse pressure.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 204,
    "Date": "2025-12-13 01:17:47 pm",
    "Sys": 138,
    "Dia": 99,
    "BPM": 84,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "Just shoveled the driveway.  Stupid winter.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 205,
    "Date": "2025-12-14 05:07:40 pm",
    "Sys": 124,
    "Dia": 86,
    "BPM": 76,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 38,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 206,
    "Date": "2025-12-15 06:01:28 pm",
    "Sys": 120,
    "Dia": 90,
    "BPM": 78,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 207,
    "Date": "2025-12-16 05:10:47 pm",
    "Sys": 127,
    "Dia": 100,
    "BPM": 74,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "Just got home from doing laundry; carried heavy bags and backpack on the bus.  Periods of lightheadedness.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 208,
    "Date": "2025-12-16 10:30:14 pm",
    "Sys": 103,
    "Dia": 74,
    "BPM": 74,
    "Workday": "No",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 29,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 209,
    "Date": "2025-12-17 05:02:10 pm",
    "Sys": 111,
    "Dia": 74,
    "BPM": 78,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 210,
    "Date": "2025-12-18 05:16:37 pm",
    "Sys": 118,
    "Dia": 82,
    "BPM": 81,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 211,
    "Date": "2025-12-19 05:52:04 pm",
    "Sys": 133,
    "Dia": 88,
    "BPM": 80,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 45,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 212,
    "Date": "2025-12-20 09:40:35 pm",
    "Sys": 129,
    "Dia": 86,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 43,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 213,
    "Date": "2025-12-21 11:30:14 pm",
    "Sys": 142,
    "Dia": 91,
    "BPM": 84,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 51,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 214,
    "Date": "2025-12-22 05:21:58 pm",
    "Sys": 149,
    "Dia": 97,
    "BPM": 74,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 52,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 215,
    "Date": "2025-12-23 08:03:35 pm",
    "Sys": 123,
    "Dia": 83,
    "BPM": 79,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 40,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 216,
    "Date": "2026-01-01 09:31:15 pm",
    "Sys": 137,
    "Dia": 98,
    "BPM": 92,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 39,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 217,
    "Date": "2026-01-02 05:50:09 pm",
    "Sys": 127,
    "Dia": 82,
    "BPM": 96,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 45,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 218,
    "Date": "2026-01-03 05:31:19 pm",
    "Sys": 114,
    "Dia": 92,
    "BPM": 90,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 22,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 219,
    "Date": "2026-01-04 08:40:30 pm",
    "Sys": 129,
    "Dia": 89,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 40,
    "FormComments": "Light Headed.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 220,
    "Date": "2026-01-05 01:23:02 pm",
    "Sys": 137,
    "Dia": 100,
    "BPM": 84,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "Just got home from work - light headed.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 221,
    "Date": "2026-01-05 06:17:17 pm",
    "Sys": 140,
    "Dia": 82,
    "BPM": 78,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 58,
    "FormComments": "Stayed still for hours after last reading; sys rose, PP rose, Dia dropped.",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 222,
    "Date": "2026-01-06 05:18:10 pm",
    "Sys": 138,
    "Dia": 96,
    "BPM": 83,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 42,
    "FormComments": "",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 223,
    "Date": "2026-01-07 05:01:14 pm",
    "Sys": 119,
    "Dia": 89,
    "BPM": 82,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 30,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 224,
    "Date": "2026-01-07 11:33:53 pm",
    "Sys": 101,
    "Dia": 76,
    "BPM": 76,
    "Workday": "Yes",
    "ReadingCategory": "Normal",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 25,
    "FormComments": "Phew, almost fell down - went from Hypertension to the first Normal reading in a looong time.  Pulse pressure is super low.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 225,
    "Date": "2026-01-08 05:31:43 pm",
    "Sys": 122,
    "Dia": 87,
    "BPM": 81,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 35,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 226,
    "Date": "2026-01-09 09:43:44 am",
    "Sys": 124,
    "Dia": 90,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "Light headed when I woke up.",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 227,
    "Date": "2026-01-09 07:45:12 pm",
    "Sys": 120,
    "Dia": 83,
    "BPM": 70,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 37,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 228,
    "Date": "2026-01-10 05:31:25 pm",
    "Sys": 118,
    "Dia": 82,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 36,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 229,
    "Date": "2026-01-11 06:06:17 pm",
    "Sys": 115,
    "Dia": 80,
    "BPM": 72,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 35,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 230,
    "Date": "2026-01-12 05:52:52 pm",
    "Sys": 139,
    "Dia": 99,
    "BPM": 75,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 40,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 231,
    "Date": "2026-01-13 05:12:00 pm",
    "Sys": 110,
    "Dia": 83,
    "BPM": 75,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 232,
    "Date": "2026-01-14 05:30:29 pm",
    "Sys": 118,
    "Dia": 92,
    "BPM": 82,
    "Workday": "Yes",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 26,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 233,
    "Date": "2026-01-15 04:59:34 pm",
    "Sys": 113,
    "Dia": 80,
    "BPM": 73,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 33,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 234,
    "Date": "2026-01-15 08:48:48 pm",
    "Sys": 108,
    "Dia": 81,
    "BPM": 68,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 27,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 235,
    "Date": "2026-01-16 09:33:17 pm",
    "Sys": 118,
    "Dia": 84,
    "BPM": 77,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 34,
    "FormComments": "",
    "PulsePressureCategory": "Narrowed"
  },
  {
    "ReadingID": 236,
    "Date": "2026-01-17 05:01:07 pm",
    "Sys": 134,
    "Dia": 91,
    "BPM": 71,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 2",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 43,
    "FormComments": "Lazy day coding away - bp and pp are high. Why?  Haven't eaten.",
    "PulsePressureCategory": "Normal"
  },
  {
    "ReadingID": 237,
    "Date": "2026-01-18 05:21:33 pm",
    "Sys": 132,
    "Dia": 71,
    "BPM": 87,
    "Workday": "No",
    "ReadingCategory": "Hypertension Stage 1",
    "PulseCategory": "Normal Pulse",
    "gPulsePressure": 61,
    "FormComments": "Whoa - highest pulse pressure to date.  No lightheadedness.",
    "PulsePressureCategory": "Widened"
  }
];